package com.bede.users.function.fighter;

import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.List;
import java.util.Random;

public class RandomNameGenerator {

    private static final List<String> males;
    private static final List<String> females;

    static {
        males = Arrays.asList(
                "James",
                "John",
                "Robert",
                "Michael",
                "William",
                "David",
                "Richard",
                "Joseph",
                "Thomas",
                "Charles",
                "Christopher",
                "Daniel",
                "Matthew",
                "Anthony",
                "Donald",
                "Mark",
                "Paul",
                "Steven",
                "Andrew",
                "Kenneth",
                "Joshua",
                "Kevin",
                "Brian",
                "George",
                "Edward",
                "Ronald",
                "Timothy",
                "Jason",
                "Jeffrey",
                "Ryan",
                "Jacob",
                "Gary",
                "Nicholas",
                "Eric",
                "Jonathan",
                "Stephen",
                "Larry",
                "Justin",
                "Scott",
                "Brandon",
                "Benjamin",
                "Samuel",
                "Frank",
                "Gregory",
                "Raymond",
                "Alexander",
                "Patrick",
                "Jack",
                "Dennis",
                "Jerry",
                "Tyler",
                "Aaron",
                "Jose",
                "Henry",
                "Adam",
                "Douglas",
                "Nathan",
                "Peter",
                "Zachary",
                "Kyle",
                "Walter",
                "Harold",
                "Jeremy",
                "Ethan",
                "Carl",
                "Keith",
                "Roger",
                "Gerald",
                "Christian",
                "Terry",
                "Sean",
                "Arthur",
                "Austin",
                "Noah",
                "Lawrence",
                "Jesse",
                "Joe",
                "Bryan",
                "Billy",
                "Jordan",
                "Albert",
                "Dylan",
                "Bruce",
                "Willie",
                "Gabriel",
                "Alan",
                "Juan",
                "Logan",
                "Wayne",
                "Ralph",
                "Roy",
                "Eugene",
                "Randy",
                "Vincent",
                "Russell",
                "Louis",
                "Philip",
                "Bobby",
                "Johnny",
                "Bradley");
        females = Arrays.asList("Mary",
                "Patricia",
                "Jennifer",
                "Linda",
                "Elizabeth",
                "Barbara",
                "Susan",
                "Jessica",
                "Sarah",
                "Karen",
                "Nancy",
                "Lisa",
                "Margaret",
                "Betty",
                "Sandra",
                "Ashley",
                "Dorothy",
                "Kimberly",
                "Emily",
                "Donna",
                "Michelle",
                "Carol",
                "Amanda",
                "Melissa",
                "Deborah",
                "Stephanie",
                "Rebecca",
                "Laura",
                "Sharon",
                "Cynthia",
                "Kathleen",
                "Amy",
                "Shirley",
                "Angela",
                "Helen",
                "Anna",
                "Brenda",
                "Pamela",
                "Nicole",
                "Samantha",
                "Katherine",
                "Emma",
                "Ruth",
                "Christine",
                "Catherine",
                "Debra",
                "Rachel",
                "Carolyn",
                "Janet",
                "Virginia",
                "Maria",
                "Heather",
                "Diane",
                "Julie",
                "Joyce",
                "Victoria",
                "Kelly",
                "Christina",
                "Lauren",
                "Joan",
                "Evelyn",
                "Olivia",
                "Judith",
                "Megan",
                "Cheryl",
                "Martha",
                "Andrea",
                "Frances",
                "Hannah",
                "Jacqueline",
                "Ann",
                "Gloria",
                "Jean",
                "Kathryn",
                "Alice",
                "Teresa",
                "Sara",
                "Janice",
                "Doris",
                "Madison",
                "Julia",
                "Grace",
                "Judy",
                "Abigail",
                "Marie",
                "Denise",
                "Beverly",
                "Amber",
                "Theresa",
                "Marilyn",
                "Danielle",
                "Diana",
                "Brittany",
                "Natalie",
                "Sophia",
                "Rose",
                "Isabella",
                "Alexis",
                "Kayla",
                "Charlotte");
    }

    public static String getMale() {
        return males.get(getRandomNumberInts(0, males.size() - 1));
    }

    public static String getFemale() {
        return females.get(getRandomNumberInts(0, females.size() - 1));
    }

    public static int getRandomNumberInts(int min, int max) {
        Random random = new Random();
        return random.ints(min, (max + 1)).findFirst().getAsInt();
    }
}
